# Generated by Django 5.2.4 on 2025-07-31 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_student_fees_period_alter_student_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='fees_period',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('half_yearly', 'Half-Yearly'), ('yearly', 'Yearly')], default='monthly', max_length=20),
        ),
    ]
