# Generated by Django 5.2.4 on 2025-08-01 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_student_amount_alter_student_fees_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='amount',
            field=models.SmallIntegerField(default=0),
        ),
    ]
