# Generated by Django 5.2.4 on 2025-08-01 11:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_alter_student_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='paid_till_date',
            field=models.DateField(default=datetime.date(1970, 1, 1)),
        ),
    ]
