# Generated by Django 5.2.4 on 2025-08-01 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_alter_student_paid_till_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='amount',
            new_name='monthly_fee',
        ),
    ]
